import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the isLoading slice
const initialState = false;

export const isLoadingSlice = createSlice({
    name: "isLoading",
    initialState,
    reducers: {
        // Reducer to set the isLoading state
        setIsLoading: (state, action) => {
            // Ensure the payload is a boolean value
            if (typeof action.payload === 'boolean') {
                return action.payload;
            } else {
                console.warn('setIsLoading payload must be a boolean');
                return state;
            }
        }
    }
});

// Export the action creator generated by createSlice
export const { setIsLoading } = isLoadingSlice.actions;

// Export the reducer to be used in the store
export default isLoadingSlice.reducer;
